name: Code Coverage

on:
    workflow_dispatch: 
    

env:
  MONGO_URI: '${{ vars.MONGO_URI }}'  # Securely stored URI in GitHub secrets    
  MONGO_PASSWORD: '${{vars.MONGO_PASSWORD}}'
  MONGO_USERNAME: '${{vars.MONGO_USERNAME}}'
    
jobs:
    code_coverage:
        name: running code coverage
        runs-on: ubuntu-latest
        steps:
            - name: check repo
              uses: actions/checkout@v4

            - name: setup node j
              uses: actions/setup-node@v3


            - name: cache npm dependenices
              uses: actions/cache@v3
              with:
                path: npm-modules
                key: ${{runner.os}}-npm-modules-${{hashFiles('packages-lock.json')}}     
              
            - name: install dependencies
              if: always()
              run:  npm install
              
            - name: run code coverage
              continue-on-error: true
              run: npm run coverage
              
            - name: upload artificats
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: naveen-art
                path: coverage
                retention-days: 5