name: Solar System Workflow

on:
  workflow_dispatch:
  
  
env:
  MONGO_URI: '${{ vars.MONGO_URI }}'  # Securely stored URI in GitHub secrets    
  MONGO_PASSWORD: '${{vars.MONGO_PASSWORD}}'
  MONGO_USERNAME: '${{vars.MONGO_USERNAME}}'
    
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
            node-js: [18, 15]
        runs-on: ${{matrix.os}}    
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-js}}
          
        - name: cache npm dependenices
          uses: actions/cache@v3
          with:
            path: npm-modules
            key: ${{runner.os}}-npm-modules-${{hashFiles('packages-lock.json')}}     
    
        - name: Install Dependencies
          continue-on-error: true
          run: npm install
    
        - name: Unit Testing
          continue-on-error: true
          run: npm test
          
        - name: Archive Test Result
          continue-on-error: true
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code_coverage:
        name: running code coverage
        runs-on: ubuntu-latest
        steps:
            - name: check repo
              uses: actions/checkout@v4

            - name: setup node j
              uses: actions/setup-node@v3


            - name: cache npm dependenices
              uses: actions/cache@v3
              with:
                path: npm-modules
                key: ${{runner.os}}-npm-modules-${{ hashFiles('packages-lock.json') }}     
              
            - name: install dependencies
              if: always()
              run:  npm install
              
            - name: run code coverage
              continue-on-error: true
              run: npm run coverage
              
            - name: upload artificats
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: naveen-art
                path: coverage
                retention-days: 5        

    Docker:
      name: login to Docker
      runs-on: ubuntu-latest
      steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: nkposa
          password: HimaB@96.
        
      - name: check login
        run: echo logged in successfully      
