name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'features/*'

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}  # Ensure this is stored in GitHub Secrets
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}  # If needed, store username as secret
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}  # Store MongoDB password as secret

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AtlasCLI
        uses: mongodb/atlas-github-action@v0.2.0
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version # Print Atlas CLI Version

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Result
          path: test-results.xml
